spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:log4jdbc:h2:mem://localhost/~/test
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update  # option type: create, create-drop, update, validate, none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect  # 쿼리의 기준이 되는 데이터베이스 엔진을 설정합니다.
        show_sql: true  # sql 쿼리를 보여줍니다.
        format_sql: true  # sql query formatting
        use_sql_comments: true  # sql 쿼리의 추가정보를 보여줍니다.

  data:
    redis:
      host: localhost
      port: 6379
    rest:
      base-path: http://localhost:8080/

jwt:
  secret: 236979CB6F1AD6B6A6184A31E6BE37DB3818CC36871E26235DD67DCFE4041492



#MyBatis -> mybatis-config.xml works
mybatis:
  config-location: classpath:mybatis-config.xml
#  configuration:
#    map-underscore-to-camel-case: true
#  type-aliases-package: com.references.member.model, com.references.common.mybatis
#  type-handlers-package: com.example.insider-back.common.mybatis
logging:
  level:
    com:
      example:
        insiderback:
          member:
            repository: trace

# actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
#        exclude: "env,beans"
  endpoint:
    shutdown:
      enabled: true
  health:
    show-details: always

custom:
  fileupload:
    path: D:/upload/insider-back

aes:
  key: 1MXH14UcdcYaXngTE3Sw00u6YsbZ2mBR
  alg: AES/CBC/PKCS5Padding